### ISSUE TITLE
Problem: Users can't discuss projects

### ISSUE THREAD

**Issue by porcellus** [EmurgoHK/c4projects#22]
I feel like we should do something like a forum for each project, as just a comment section below a project (especially if it's going for long) can quickly get chaotic and/or swamp users with notifications.
ping @gazhayes

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by gazhayes** [comment]
It's ok, this is going a bit far at this point. This just needs to be a very simple place to track c4 projects, bare minimum. Notifications and discussions are aready borderline.

**Comment by porcellus** [comment]
Ok, I'll close this then.
